export type ExerciseCategory = "push" | "pull" | "legs" | "core";

export interface Exercise {
  name: string;
  category: ExerciseCategory;
}

export const EXERCISES: Exercise[] = [
  // Push — chest, shoulders, triceps
  { name: "Bench Press", category: "push" },
  { name: "Incline Bench Press", category: "push" },
  { name: "Decline Bench Press", category: "push" },
  { name: "Close-Grip Bench Press", category: "push" },
  { name: "Dumbbell Chest Press", category: "push" },
  { name: "Incline Dumbbell Press", category: "push" },
  { name: "Machine Chest Press", category: "push" },
  { name: "Smith Machine Bench Press", category: "push" },
  { name: "Push-Ups", category: "push" },
  { name: "Diamond Push-Ups", category: "push" },
  { name: "Cable Crossover", category: "push" },
  { name: "Cable Fly", category: "push" },
  { name: "Chest Fly Machine", category: "push" },
  { name: "Pec Deck", category: "push" },
  { name: "Dumbbell Fly", category: "push" },
  { name: "Overhead Press", category: "push" },
  { name: "Seated Barbell Press", category: "push" },
  { name: "Dumbbell Shoulder Press", category: "push" },
  { name: "Arnold Press", category: "push" },
  { name: "Machine Shoulder Press", category: "push" },
  { name: "Landmine Press", category: "push" },
  { name: "Lateral Raises", category: "push" },
  { name: "Cable Lateral Raise", category: "push" },
  { name: "Front Raises", category: "push" },
  { name: "Upright Row", category: "push" },
  { name: "Reverse Pec Deck", category: "push" },
  { name: "Tricep Pushdown", category: "push" },
  { name: "Rope Pushdown", category: "push" },
  { name: "Overhead Tricep Extension", category: "push" },
  { name: "Skull Crushers", category: "push" },
  { name: "Dips", category: "push" },
  { name: "Bench Dips", category: "push" },
  { name: "Tricep Kickback", category: "push" },

  // Pull — back, biceps, rear delts
  { name: "Deadlift", category: "pull" },
  { name: "Romanian Deadlift", category: "pull" },
  { name: "Sumo Deadlift", category: "pull" },
  { name: "Rack Pulls", category: "pull" },
  { name: "Barbell Row", category: "pull" },
  { name: "Pendlay Row", category: "pull" },
  { name: "T-Bar Row", category: "pull" },
  { name: "Dumbbell Row", category: "pull" },
  { name: "Chest-Supported Row", category: "pull" },
  { name: "Seated Cable Row", category: "pull" },
  { name: "Lat Pulldown", category: "pull" },
  { name: "Wide-Grip Lat Pulldown", category: "pull" },
  { name: "Close-Grip Lat Pulldown", category: "pull" },
  { name: "Straight-Arm Pulldown", category: "pull" },
  { name: "Pull-Ups", category: "pull" },
  { name: "Chin-Ups", category: "pull" },
  { name: "Assisted Pull-Ups", category: "pull" },
  { name: "Face Pulls", category: "pull" },
  { name: "Shrugs", category: "pull" },
  { name: "Dumbbell Shrugs", category: "pull" },
  { name: "Barbell Curl", category: "pull" },
  { name: "EZ Bar Curl", category: "pull" },
  { name: "Dumbbell Curl", category: "pull" },
  { name: "Hammer Curl", category: "pull" },
  { name: "Cable Curl", category: "pull" },
  { name: "Preacher Curl", category: "pull" },
  { name: "Incline Dumbbell Curl", category: "pull" },
  { name: "Concentration Curl", category: "pull" },
  { name: "Spider Curl", category: "pull" },

  // Legs — quads, hamstrings, glutes, calves
  { name: "Squat", category: "legs" },
  { name: "Front Squat", category: "legs" },
  { name: "Box Squat", category: "legs" },
  { name: "Pause Squat", category: "legs" },
  { name: "Goblet Squat", category: "legs" },
  { name: "Hack Squat", category: "legs" },
  { name: "Smith Machine Squat", category: "legs" },
  { name: "Leg Press", category: "legs" },
  { name: "Single-Leg Press", category: "legs" },
  { name: "Belt Squat", category: "legs" },
  { name: "Leg Extension", category: "legs" },
  { name: "Leg Curl", category: "legs" },
  { name: "Seated Leg Curl", category: "legs" },
  { name: "Lying Leg Curl", category: "legs" },
  { name: "Stiff-Leg Deadlift", category: "legs" },
  { name: "Good Mornings", category: "legs" },
  { name: "Hip Thrust", category: "legs" },
  { name: "Glute Bridge", category: "legs" },
  { name: "Cable Kickback", category: "legs" },
  { name: "Hip Abduction Machine", category: "legs" },
  { name: "Bulgarian Split Squat", category: "legs" },
  { name: "Lunges", category: "legs" },
  { name: "Walking Lunges", category: "legs" },
  { name: "Reverse Lunges", category: "legs" },
  { name: "Step-Ups", category: "legs" },
  { name: "Calf Raises", category: "legs" },
  { name: "Seated Calf Raises", category: "legs" },
  { name: "Donkey Calf Raises", category: "legs" },

  // Core
  { name: "Plank", category: "core" },
  { name: "Side Plank", category: "core" },
  { name: "Hanging Leg Raises", category: "core" },
  { name: "Cable Crunch", category: "core" },
  { name: "Ab Wheel Rollout", category: "core" },
  { name: "Russian Twist", category: "core" },
  { name: "Decline Sit-Up", category: "core" },
  { name: "Crunches", category: "core" },
  { name: "Mountain Climbers", category: "core" },
  { name: "Pallof Press", category: "core" },
  { name: "Wood Chop", category: "core" },
  { name: "Dead Bug", category: "core" },
];

export const CATEGORY_LABELS: Record<ExerciseCategory, string> = {
  push: "Push",
  pull: "Pull",
  legs: "Legs",
  core: "Core",
};

export const CATEGORY_COLORS: Record<ExerciseCategory, string> = {
  push: "text-primary",
  pull: "text-blue-400",
  legs: "text-orange-400",
  core: "text-purple-400",
};
